# Generated by Django 3.0.4 on 2020-06-19 07:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactsgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'contact group',
                'verbose_name_plural': 'contact groups',
            },
        ),
        migrations.CreateModel(
            name='Contactstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'contact type',
                'verbose_name_plural': 'contact types',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('links', models.CharField(blank=True, max_length=250, verbose_name='links')),
                ('comments', models.TextField(blank=True, max_length=2500, verbose_name='comments')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('attached', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Listing', verbose_name='attached listing')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contactsgroup', verbose_name='group')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contactstype', verbose_name='owner type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
