# Generated by Django 3.0.4 on 2020-04-18 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contactsgroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='links',
            field=models.CharField(blank=True, max_length=250, verbose_name='links'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contactstype', verbose_name='owner type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='business',
            field=models.CharField(blank=True, max_length=250, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='links',
            field=models.CharField(blank=True, max_length=70, verbose_name='links'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pics', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='publicmail',
            field=models.CharField(blank=True, max_length=100, verbose_name='public email'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserType', verbose_name='users_group'),
        ),
    ]
