# Generated by Django 3.0.4 on 2020-06-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='attached',
        ),
    ]
