# Generated by Django 3.0.4 on 2020-06-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_contact_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(max_length=2500, verbose_name='comments'),
        ),
    ]
