# Generated by Django 3.0.4 on 2020-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200418_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactstype',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
