# Generated by Django 3.0.4 on 2020-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200420_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='title_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
