# Generated by Django 3.0.4 on 2020-04-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usertype_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, max_length=1500, verbose_name='comments'),
        ),
    ]
