# Generated by Django 3.0.4 on 2020-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200422_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, max_length=2500, verbose_name='comments'),
        ),
    ]
