# Generated by Django 3.0.4 on 2020-04-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserType', verbose_name='users_group'),
        ),
    ]
