# Generated by Django 3.0.4 on 2020-04-30 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200428_0126'),
        ('users', '0007_auto_20200422_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing', verbose_name='attached listing'),
        ),
        migrations.AlterField(
            model_name='Profile',
            name='usertype',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.DO_NOTHING, to='users.UserType', verbose_name='users_group'),
        ),
    ]
