# Generated by Django 3.0.4 on 2020-05-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200501_1751'),
        ('users', '0008_auto_20200424_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Listing', verbose_name='attached listing'),
        ),
    ]
