# Generated by Django 3.0.4 on 2020-06-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contact_attached'),
        ('users', '0009_auto_20200501_1403'),
        ('users', '0008_auto_20200424_2030'),
    ]

    operations = [
    ]
