# Generated by Django 3.0.4 on 2020-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200611_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='company address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_email',
            field=models.CharField(blank=True, max_length=150, verbose_name='company email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_vk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_website',
            field=models.CharField(blank=True, max_length=200, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ad_youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='publicmail',
            field=models.CharField(blank=True, max_length=100, verbose_name='blog email'),
        ),
    ]
