# Generated by Django 3.0.4 on 2020-06-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_listing_breed'),
        ('users', '0011_auto_20200611_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing', verbose_name='attached listing'),
        ),
    ]
