# Generated by Django 3.0.4 on 2020-06-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20200612_0035'),
        ('users', '0013_auto_20200612_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing', verbose_name='attached listing'),
        ),
    ]
