# Generated by Django 3.0.4 on 2020-06-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20200612_0042'),
        ('users', '0014_auto_20200612_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Listing', verbose_name='attached listing'),
        ),
    ]
