# Generated by Django 3.0.4 on 2020-06-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200612_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
