# Generated by Django 3.0.4 on 2020-06-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200615_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsgroup',
            options={'verbose_name': 'contact group', 'verbose_name_plural': 'contact groups'},
        ),
        migrations.AlterModelOptions(
            name='contactstype',
            options={'verbose_name': 'contact type', 'verbose_name_plural': 'contact types'},
        ),
    ]
