# Generated by Django 3.0.4 on 2020-06-19 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ad status',
                'verbose_name_plural': 'ad statuses',
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'age',
                'verbose_name_plural': 'age',
            },
        ),
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'breeds',
                'verbose_name_plural': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'health',
                'verbose_name_plural': 'health',
            },
        ),
        migrations.CreateModel(
            name='Taps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(max_length=150, verbose_name='contacts')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('district', models.CharField(max_length=30, verbose_name='district')),
                ('price', models.IntegerField(verbose_name='price')),
                ('video', models.CharField(blank=True, max_length=300, verbose_name='youtube')),
                ('description', models.TextField(blank=True, max_length=2500, verbose_name='description')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created')),
                ('archived', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='main photo')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_4')),
                ('adstatus_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Adstatus')),
                ('age_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Age', verbose_name='age')),
                ('breeds', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Breeds', verbose_name='breeds')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Category', verbose_name='category')),
                ('conditions_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Condition', verbose_name='conditions')),
            ],
        ),
    ]
