# Generated by Django 3.0.4 on 2020-04-19 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200418_2326'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_ru', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Taps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='is_archived',
            new_name='is_featured',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='age',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user_id',
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condition',
            name='title_ru',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='title_ru',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='title_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='archived',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Contact', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='user_contact',
            field=models.CharField(default=1, max_length=150, verbose_name='contacts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='breed'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=20, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='conditions_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Condition', verbose_name='conditions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(max_length=30, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='gender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Gender', verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='health_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Health', verbose_name='health'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_3'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_4'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='main photo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='breeds',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Taps'),
        ),
        migrations.AddField(
            model_name='listing',
            name='adstatus_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Adstatus'),
        ),
        migrations.AddField(
            model_name='listing',
            name='age_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Age', verbose_name='age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='types_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.Taps', verbose_name='type'),
            preserve_default=False,
        ),
    ]
