# Generated by Django 3.0.4 on 2020-06-19 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='forester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_foster', to='users.Contact', verbose_name='forester'),
        ),
        migrations.AddField(
            model_name='listing',
            name='gender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Gender', verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='listing',
            name='health_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Health', verbose_name='health'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_owner', to='users.Contact', verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='listing',
            name='types_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Taps', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='breeds',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Taps'),
        ),
    ]
