# Generated by Django 3.0.4 on 2020-04-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200419_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='breeds',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Breeds', verbose_name='breeds'),
            preserve_default=False,
        ),
    ]
