# Generated by Django 3.0.4 on 2020-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_breeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='breed',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='breed'),
        ),
    ]
