# Generated by Django 3.0.4 on 2020-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('listings', '0003_auto_20200622_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='requests',
            field=models.ManyToManyField(blank=True, to='users.Contact'),
        ),
    ]
