# Generated by Django 3.0.4 on 2020-04-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200422_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='/img/avatar-animal.png', upload_to='photos/%Y/%m/%d/', verbose_name='main photo'),
        ),
    ]
