# Generated by Django 3.0.4 on 2020-04-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200428_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='./static/img/avatar-animal.svg', upload_to='photos/%Y/%m/%d/', verbose_name='main photo'),
        ),
    ]
