# Generated by Django 3.0.4 on 2020-05-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200430_2340'),
        ('listings', '0014_auto_20200428_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='forester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contact', verbose_name='forester'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_owner', to='users.Contact', verbose_name='owner'),
        ),
    ]
