# Generated by Django 3.0.4 on 2020-06-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20200501_1403'),
        ('listings', '0015_auto_20200501_1751'),
    ]

    operations = [
    ]
