# Generated by Django 3.0.4 on 2020-06-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_merge_20200611_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='forester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing_foster', to='users.Contact', verbose_name='forester'),
        ),
    ]
