# Generated by Django 3.0.4 on 2020-06-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20200611_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.CharField(blank=True, max_length=300, verbose_name='youtube'),
        ),
    ]
