# Generated by Django 3.0.4 on 2020-06-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='breed',
        ),
    ]
