# Generated by Django 3.0.4 on 2020-06-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0019_remove_listing_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='types_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Taps', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='created'),
        ),
    ]
