# Generated by Django 3.0.4 on 2020-06-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200612_0038'),
        ('listings', '0020_auto_20200612_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='forester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_foster', to='users.Contact', verbose_name='forester'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_owner', to='users.Contact', verbose_name='owner'),
        ),
    ]
