# Generated by Django 3.0.4 on 2020-06-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20200612_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adstatus',
            options={'verbose_name': 'ad status', 'verbose_name_plural': 'ad statuses'},
        ),
        migrations.AlterModelOptions(
            name='breeds',
            options={'verbose_name': 'breeds', 'verbose_name_plural': 'breeds'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name': 'health', 'verbose_name_plural': 'health'},
        ),
        migrations.AlterModelOptions(
            name='taps',
            options={'verbose_name': 'type', 'verbose_name_plural': 'types'},
        ),
    ]
