# Generated by Django 3.0.4 on 2020-06-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20200616_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'age', 'verbose_name_plural': 'age'},
        ),
    ]
