# Generated by Django 3.0.4 on 2020-06-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200622_1734'),
        ('carts', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='listings',
            field=models.ManyToManyField(blank=True, to='listings.Listing'),
        ),
    ]
