# Generated by Django 3.0.4 on 2020-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
    ]
