# Generated by Django 3.0.4 on 2020-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('middletext', models.CharField(max_length=300)),
                ('middletext_ru', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('title_ru', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True)),
                ('content_ru', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_ru', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('content_ru', models.CharField(max_length=500)),
            ],
        ),
    ]
