# Generated by Django 3.0.4 on 2020-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_ru', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('content_ru', models.CharField(max_length=500)),
            ],
        ),
    ]
