# Generated by Django 3.0.4 on 2020-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_welcometext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('middletext', models.CharField(max_length=300)),
                ('middletext_ru', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
