# Generated by Django 3.0.4 on 2020-06-19 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('key', models.CharField(blank=True, max_length=120, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('forced_expired', models.BooleanField(default=False)),
                ('expires', models.IntegerField(default=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('publicmail', models.CharField(blank=True, max_length=100, verbose_name='blog email')),
                ('business', models.CharField(blank=True, max_length=250, verbose_name='organization name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('links', models.CharField(blank=True, max_length=70, verbose_name='links')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='details')),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='photo')),
                ('ad_organization', models.CharField(blank=True, max_length=200, verbose_name='organization')),
                ('ad_address', models.CharField(blank=True, max_length=200, verbose_name='company address')),
                ('ad_website', models.CharField(blank=True, max_length=200, verbose_name='website')),
                ('ad_email', models.CharField(blank=True, max_length=150, verbose_name='company email')),
                ('ad_youtube', models.CharField(blank=True, max_length=200)),
                ('ad_facebook', models.CharField(blank=True, max_length=200)),
                ('ad_vk', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
