# Generated by Django 3.0.4 on 2020-06-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, max_length=100, verbose_name='users type subtitute'),
        ),
    ]
