# Generated by Django 3.0.4 on 2020-06-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.UserType', verbose_name='users_group'),
        ),
    ]
