# Generated by Django 3.0.4 on 2020-06-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='users_group')),
                ('publicmail', models.CharField(blank=True, max_length=100, verbose_name='blog email')),
                ('business', models.CharField(blank=True, max_length=250, verbose_name='organization name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('links', models.CharField(blank=True, max_length=70, verbose_name='links')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='details')),
                ('photo', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='photo')),
                ('ad_organization', models.CharField(blank=True, max_length=200, verbose_name='organization')),
                ('ad_address', models.CharField(blank=True, max_length=200, verbose_name='company address')),
                ('ad_website', models.CharField(blank=True, max_length=200, verbose_name='website')),
                ('ad_email', models.CharField(blank=True, max_length=150, verbose_name='company email')),
                ('ad_youtube', models.CharField(blank=True, max_length=200)),
                ('ad_facebook', models.CharField(blank=True, max_length=200)),
                ('ad_vk', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
