# Generated by Django 3.0.4 on 2020-07-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sponsor',
            field=models.BooleanField(default=False),
        ),
    ]
