# Generated by Django 3.0.4 on 2020-06-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_emailactivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailactivation',
            old_name='timastamp',
            new_name='timestamp',
        ),
    ]
