# Generated by Django 3.0.4 on 2020-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='title')),
                ('title', models.CharField(max_length=200, verbose_name='title eng')),
                ('content_ru', models.CharField(max_length=2000, verbose_name='content')),
                ('content', models.CharField(max_length=2000, verbose_name='content eng')),
            ],
        ),
    ]
