# Generated by Django 3.0.4 on 2020-06-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='content',
            field=models.TextField(blank=True, max_length=3000, verbose_name='content eng'),
        ),
        migrations.AlterField(
            model_name='guidance',
            name='content_ru',
            field=models.TextField(blank=True, max_length=3000, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='content',
            field=models.TextField(blank=True, max_length=2500, verbose_name='content eng'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='content_ru',
            field=models.TextField(blank=True, max_length=2500, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title eng'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='title_ru',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
