# Generated by Django 3.0.4 on 2020-06-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20200627_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='content',
            field=models.TextField(blank=True, max_length=1000, verbose_name='content eng'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='content_ru',
            field=models.TextField(blank=True, max_length=1000, verbose_name='content'),
        ),
    ]
