# Generated by Django 3.0.4 on 2020-06-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20200627_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='content eng'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='content_ru',
            field=models.TextField(blank=True, max_length=2000, verbose_name='content'),
        ),
    ]
