# Generated by Django 3.0.4 on 2020-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
        migrations.AddField(
            model_name='themes',
            name='slug',
            field=models.SlugField(blank=True, max_length=400),
        ),
    ]
