# Generated by Django 3.0.4 on 2020-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200702_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='slug',
            field=models.SlugField(max_length=400, unique=True),
        ),
    ]
