# Generated by Django 3.0.4 on 2020-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200702_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='themes',
            name='slug',
            field=models.SlugField(blank=True, max_length=400),
        ),
    ]
