# Generated by Django 3.0.4 on 2020-04-18 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200419_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 22, 2, 24, 659427, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 22, 2, 24, 657427, tzinfo=utc), verbose_name='created'),
        ),
    ]
