# Generated by Django 3.0.4 on 2020-04-18 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200419_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 22, 6, 51, 985802, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 22, 6, 51, 983808, tzinfo=utc), verbose_name='created'),
        ),
    ]
