# Generated by Django 3.0.4 on 2020-04-20 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200419_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 8, 40, 30, 979119, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 8, 40, 30, 979119, tzinfo=utc), verbose_name='created'),
        ),
    ]
