# Generated by Django 3.0.4 on 2020-04-20 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200420_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 42, 44, 763688, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=500, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 13, 42, 44, 762696, tzinfo=utc), verbose_name='created'),
        ),
    ]
