# Generated by Django 3.0.4 on 2020-04-20 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20200420_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 43, 43, 455342, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 13, 43, 43, 439727, tzinfo=utc), verbose_name='created'),
        ),
    ]
