# Generated by Django 3.0.4 on 2020-04-20 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200420_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='title_ru',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 56, 12, 947319, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 13, 56, 12, 945320, tzinfo=utc), verbose_name='created'),
        ),
    ]
