# Generated by Django 3.0.4 on 2020-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200421_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1500, verbose_name='message'),
        ),
    ]
