# Generated by Django 3.0.4 on 2020-07-18 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ad status',
                'verbose_name_plural': 'ad statuses',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(max_length=150, verbose_name='contacts')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('applicants_number', models.IntegerField(default='1', verbose_name='applicants number')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('is_featured', models.BooleanField(default=False)),
                ('adstatus_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Adstatus')),
                ('requests', models.ManyToManyField(blank=True, related_name='user_requests', to='companies.Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='created')),
            ],
            options={
                'verbose_name': 'proposal',
                'verbose_name_plural': 'proposals',
            },
        ),
    ]
