# Generated by Django 3.0.4 on 2020-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adstatus',
            new_name='Propstatus',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='companies.Application'),
        ),
    ]
