# Generated by Django 3.0.4 on 2020-07-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200719_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, max_length=1500, verbose_name='description'),
        ),
    ]
