# Generated by Django 3.0.4 on 2020-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200719_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='approvals', to='companies.Proposal'),
        ),
    ]
