# Generated by Django 3.0.4 on 2020-06-22 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ad status',
                'verbose_name_plural': 'ad statuses',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_ru', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_contact', models.CharField(max_length=150, verbose_name='contacts')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.IntegerField(verbose_name='price')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='description')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='created')),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='main photo')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='photo_4')),
                ('adstatus_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='products.Adstatus')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.ProductCategory', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created')),
            ],
        ),
    ]
