# Generated by Django 3.0.4 on 2020-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
