# Generated by Django 3.0.4 on 2020-06-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
    ]
