# Generated by Django 3.0.4 on 2020-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_photo_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=110, verbose_name='title'),
        ),
    ]
